use_frameworks!

platform :ios, '10.0'

target 'OCExample' do
  pod 'Fastboard', :path => '../'
  end

target 'Fastboard_Example' do
  pod 'Fastboard', :path => '../'

  target 'Fastboard_Tests' do
    inherit! :search_paths
  end
end
