use_frameworks!

platform :ios, '10.0'

def share
  pod 'Fastboard', :path => '../'
  pod 'Fastboard/fpa', :path => '../'
  pod 'Whiteboard', :git => 'https://github.com/vince-hz/Whiteboard-iOS.git', :branch => 'feature/fpa'
  pod 'Whiteboard/fpa', :git => 'https://github.com/vince-hz/Whiteboard-iOS.git', :branch => 'feature/fpa'
end
  

target 'OCExample' do
  share
  pod 'Masonry'
end

target 'Fastboard_Example' do
  share
  pod 'SnapKit'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
