use_frameworks!

platform :ios, '11.0'

def share
  pod 'Fastboard', :path => '../'
end


target 'OCExample' do
  share
  pod 'Masonry'
end

target 'Fastboard_Example' do
  share
  pod 'SnapKit'
end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
   end
end
